// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TaxationUIClient is the client API for TaxationUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaxationUIClient interface {
	// ListEngineSpecs returns a list of Taxation Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (TaxationUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type taxationUIClient struct {
	cc grpc.ClientConnInterface
}

func NewTaxationUIClient(cc grpc.ClientConnInterface) TaxationUIClient {
	return &taxationUIClient{cc}
}

func (c *taxationUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (TaxationUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &TaxationUI_ServiceDesc.Streams[0], "/v1.TaxationUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &taxationUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TaxationUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type taxationUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *taxationUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *taxationUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.TaxationUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaxationUIServer is the server API for TaxationUI service.
// All implementations must embed UnimplementedTaxationUIServer
// for forward compatibility
type TaxationUIServer interface {
	// ListEngineSpecs returns a list of Taxation Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, TaxationUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedTaxationUIServer()
}

// UnimplementedTaxationUIServer must be embedded to have forward compatible implementations.
type UnimplementedTaxationUIServer struct {
}

func (UnimplementedTaxationUIServer) ListEngineSpecs(*ListEngineSpecsRequest, TaxationUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedTaxationUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedTaxationUIServer) mustEmbedUnimplementedTaxationUIServer() {}

// UnsafeTaxationUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaxationUIServer will
// result in compilation errors.
type UnsafeTaxationUIServer interface {
	mustEmbedUnimplementedTaxationUIServer()
}

func RegisterTaxationUIServer(s grpc.ServiceRegistrar, srv TaxationUIServer) {
	s.RegisterService(&TaxationUI_ServiceDesc, srv)
}

func _TaxationUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TaxationUIServer).ListEngineSpecs(m, &taxationUIListEngineSpecsServer{stream})
}

type TaxationUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type taxationUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *taxationUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _TaxationUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaxationUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.TaxationUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaxationUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaxationUI_ServiceDesc is the grpc.ServiceDesc for TaxationUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaxationUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.TaxationUI",
	HandlerType: (*TaxationUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _TaxationUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _TaxationUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "taxation-ui.proto",
}
